import { describe, expect, it } from 'vitest';
import { deepgramConfigured, transcribe } from '../src/deepgram-client.js';

/**
 * The one test that actually calls Deepgram. Skipped, not failed, without a key -- the same
 * pattern openai-client.live.test.ts established, so a contributor without credentials is
 * never blocked from running the suite:
 *
 *   DEEPGRAM_API_KEY=... pnpm --filter @loopcraft/providers exec vitest run test/deepgram-client.live.test.ts
 *
 * The fixture below is real recorded speech ("Testing one two three."), synthesized with
 * macOS `say` at 8 kHz mono LEI16 and embedded as base64 so this test depends on no
 * microphone, no external file, and no network fetch other than Deepgram itself. It is what
 * proves the transcript AND the word-timing conversion in deepgram-client.ts are correct
 * against the live API -- the units the worker's delivery metrics are computed from. The
 * contract tests prove the parsing shape; only this proves Deepgram still matches it.
 */
const SPEECH_WAV_BASE64 =
  'UklGRkxVAABXQVZFSlVOSxwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAZm10IBAAAAABAAEAQB8AAIA+AAACABAA' +
  'RkxMUqgPAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABkYXRhVEUAAAAA//8AAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAP//AAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP//AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAA/////wAA////////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAEAAAAAAAAAAAAAAAEA' +
  'AQABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP//AAAAAP////8AAAAAAAAAAP////8AAP//AAAAAAAA' +
  'AAAAAAAAAAAAAAEAAQABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAD/////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAA//8AAAAAAAAAAP///////wAAAAAAAAAA//8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAA' +
  '//8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP//AAAAAAAAAAAAAAAAAAABAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAQABAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA////////AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD//wAA' +
  'AAD//wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAEA' +
  'AAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAA//8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP//AAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAP//AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/////wAAAAD//wAAAAAAAAAAAAAAAAAAAAAAAP//' +
  '//8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAD//wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//8AAAAAAAAAAAAA' +
  'AAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/////wAA/////wAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAEAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAA' +
  'AAAAAAAAAAAAAP//AAAAAAAAAAAAAAAAAAAAAAAAAAD//////////wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAQABAAEAAQABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD//wAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD///////8AAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAA//8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//8AAAAAAAAAAAAA//8AAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD//wAAAAAAAP////8AAAAAAAAAAAAAAAAAAP//' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAQABAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD//wAAAAAAAAAAAAAAAAAAAAAAAAAAAAD//////////wAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP//AAAAAP///////////////wAA/////wAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAEAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAP//AAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//8AAP//' +
  '//8AAAAAAAAAAAAAAAAAAAAAAAAAAP//////////AAAAAAAAAAAAAAAAAAAAAAEAAQABAAEAAAABAAEAAQACAAEAAgABAAIA' +
  'AgACAAIAAgABAAAAAAAAAAAAAAAAAAAAAAAAAAAA//////////8AAAAAAQAAAP////8AAP//////////////////AAAAAAAA' +
  'AQAAAAEAAQAAAAAAAwACAAMABAAEAAQABAAEAAMAAgACAAEAAQABAAEAAAAAAP7//v/9//z/+//6//j/9v/1//T/8v/x//H/' +
  '8f/w//D/8P/w//D/7//t/+7/7f/u/+7/7f/s/+3/7v/v//H/8//z//b/+P/7//7/AAACAAYACQANAA8AEgAWABkAGwAdAB4A' +
  'IAAfACAAIQAiACIAIwAiACUAIwAkACMAIgAiACIAIwAgAB0AGwAaABUAEgAQAA4ACwAKAAoADgAKAAUAAwD+//v//P/3//b/' +
  '8f/l/97/m/+v/77/pP+//73/pf+n/+L/PQGPBhMEQwPGAqAAu/9Y/1b/zv+K/zYA9f+0/+H/mwD7AD4AZADAAGr/7f92/vb+' +
  'Cv85/7r/yf+X/wb/6/7o/if+3P7r+6H8Rv2g/BX7qfyt/EH+jP+YAQIAuf5M/Un95f/5/f//tP+M/rMAif/uAOD/iAKzAXYB' +
  'vgAHAqsA/wAnAd8AmgFkAUICJQGKAu8BNwFiAs4AAAE/AxEBfAJHAVsCtgLKAWYAdAKCACwA3wEOAYAA4gEf/7wBoQCHAMgB' +
  'BAEP/zkBif5z/kUAXP9d/4T/c/6A//7+zf3+/qz+m/2kAK7+Jf5FAFT+Q/7k/43/Av57/tn/zP2lAN/+Nv+1AAr/zv38AKL9' +
  '3f9c/9H/ev5YAK/9EgAq/xD/qwHX/0kAQQB2AJ4APQB1/z3+DwD5/kMBP/8qAYwBdf/B/xAB2f9LAWIBUP9CASIAwf+M/5MB' +
  'iP9uAZoAbf/cADYABP+q/1QAlgBrAMAAcP8PAdMAQv9uAYH+RgHi/vUAqwAlAdr/nADn//gAmP4HAg8ARwFU/5wArP71AOT+' +
  '1f6NAOMAbQFA/58BOv/nAPD+RP+sAcUA+//eAYUAwv7J/pv/J/+dAS0A//49AVEBLv+dAKT/xAAe/2v+l/5uAI//bf9g/xUA' +
  'XgJ7/xD+IAHG/xIAjf+i/8IB8gAw/jEACAH7/hAAfP6v/R8BdAD9/sb/df7L/wsAlv5uAEkCygCHAAn/RP5q/w0AKQAkAAUA' +
  'pAGLACMBvwF9/9n/oQCqABgANQGUAXgEMgKUAfIDnQGk/fEAUQAjAaT/e/4L/kUAovur+rn7cfuE+zv6ifhw+Yz5ovn6+Zn6' +
  'Qf2H/eP6R/zT/Zj/rQG1AUQDLwcQCMQH2wkGCtgLOAw2C4EMegyUCNcHmweRBncFsQX3BIMFFQM3AJ0AQQD8/dv6Y/hb97L2' +
  'IPNl8hXz9vGC78fsSe3V7kLtZO2k8UT3lvpkADMFywowD2gNcgmmBw0GHgMsAhkBGARDCL4JuwqDDlYPPA9EDsULfAuVDIYJ' +
  'EQi6CKsIfAhLBpgDkwJQANT92/tD+UH0PvAm7LHni+Jz3YTXhNXL2HLhLPwvHEgjMSHyHpkbORJgAdnuOuyk7kHqxOg38H/+' +
  'HBEhGhsbrR7oHKcP9f8k9xv36/wR++f6HwiWFZMZzhjYFSgVLQ/r/t315fnX/XT8U/jN9Vb1ou283SDU89Lw0+rUuuDZCms1' +
  'LDFjIpgcfRqKDjP1A9kT3KTo7ejw6MD1kA4sKOgoaBtpF14TQf9R5z7e+Oc1+cH/2gIoE7QpMy1iHRgNcAerAQ7yIeIU6c0A' +
  'CA+XDIIKThC4EfwCs+p44LHlJOWz3f7iIwbgLBAo4BPnC2IMPgMl7bvPoM6F4BvkLtzz4w4TjkmdO+gaoA00DhsHgvA8wj7J' +
  'e/FrABD/lwlRFis3sjtyDy7zlfPQ7SDletdh1+X/9SIiIlMfyiJ7IBkYtPse4zTpr/Vh9YL9mAmPGHIjmBbnAqv+ePb46HTd' +
  'h9Y822Lh5ttA2afs4ykZUXIpFhOnEbcM7fvG4VK3ydVI/UUCpgCQFMAf5ji9L7n/6+mY8Q7r+eFq2hPipQpoKAYhDRpLH1ca' +
  'Gg2M9HDh+uzyAM/+9QA1DZIYcCE4FVL6BfNy9xXvN+Wg3D3aieOs577ett3DBLRGrzybFogJ5gmEA5v+DcvpwkjuWQixALYF' +
  'gwqEKSQ+qxns9LP1gPlz8zvkvNXm8WIYExtFEcIVAhwaIR8QWPKf7+r97f3j+Zj4WQCmEykUPAFI+aH6Jfnb8Brgvdfi2h7a' +
  'kNdg5GsOGjI0Ks0XQhKnENYMlveI32TjOvQv+Yv4p/ikA+sZjR4OEkwLWgtfC0kGdfha9JEAagkXCisIHQmRDygRVAjFAbMB' +
  'EwIzAGT7RvgH+4H9R/wl+rP4vvnq+MrzDe0P5rfgLt9B4NboyPdYAiwGpgmyDOQPdhDFC4MH0gVFBUME+wBg/zMC+AX0CHYK' +
  'nAm5CmoLGAmpBm0FMAbWB14I3QcKCOIHVAZ3A93/8/2s/Jn7w/uV+3/6GPv7+8P7ivqj+AP2VvJe7rjq5ejR6sHuuvKL9sz6' +
  '3v/tAmEDZQSEBeEGUQj0B2IHAAgOCCEJXwpvCYIIPwcIBikGigVkBacFYAUqBl4HcwVnBdYEuQOWA2ECuADmAOMA2f5H/Yj8' +
  'qvvd+936LPkc+O/3xvbf9+32tPXB9Y72M/Zf+OL3AflP/HL8b/7X/pz+3gAiAp8CJwPABCgFmQV5BbAGgAbCB1QHaAcpBqoG' +
  'ugaeBe8DwAMyBEEDJQMIA/0BRALOAbYA4P6F/77/cf8Z/jn+kf7v/ML8hf09+5H9Q/vb+vH7A/ug+vn7Kfs6++D9a/xD/ev8' +
  'GP1o/lH+a/7U/1AA2gBbAB0BtgHuAb0CgwJKAx8DxgOdA6kDAgPzAqcCgQJzAlMDBQJZAu0BEwIwAZwA+gDIALsA0v9sAML/' +
  'Wv80AML/4P61/879oP7Y/nP+sf2e/nD+p/3k/d39Hf/I/d7+wf7S/sv+EP+7/uj+7v5B/xEAyf+n/wEBcf/PADQAnQBTAbIB' +
  'zgClATABMQEBAdsA/QH6AOYAEgAWAYMAWQDAAGgA+/8IAT0AoP/X/wYA9P/T/4H/MgBHAEf/UwC2/6L/CwDe/yH/6P+T/9//' +
  'BQCA/5P/CgCy/9z/xv+K/1cAEwCo/6cAJwAtAPn/ZwDf/yMABAB0AOL/iwBhALf/BwBOAJv/ZwAIAPL/KAD6/1P/KADK/1kA' +
  'AACT/0IA6/8mAKcAJv9oABMAXf/K/0gAFgCHAGD/IgBPAPT/uP8RAJz/vgDr/73/mwDV/1H/RgDh/wQAPAANAG3/pAAHAP//' +
  '6/9LADMApADe/53/nACY/3oAkf9rAHQAov+h/7UAjf+5/zQAwf+9/3QAoP+pAMb/hP8MAHgAQ/+FABIAUf8zAEcAav8FABYA' +
  '8v9cAKv/NgDw/0oA5f8XABUAKQBd/14APgDR/0IAIwAqAMv/eADk/9f/EwAaAGoAZP9AAD0Awv/I/1sArv/HANH/AQAmANb/' +
  'OQB8AND/3v8QAAAAwf9yAKL/UgC9/+D/SgDV//r/JABT/ywAOgBx/4EA+P/F/zIAbgCi/6r/YACp/0EACgDI/woAy/8fAM3/' +
  'hQCw/yQALAAAAOL/QADb/9P/mADY/+7/TQAPALH/bQCO/+//hACz//7/MwD2/+T/IwDV/zoA+/+F/0gA1P/S/0MAxP/k/04A' +
  'wv8ZAPX/BADi/1AABQCk/yoA/v/P//b/BQDZ/wAAIwC1//f/AgDg/+3/IQDJ/wgABwAHABMAJQDn/x4ABAAKAAgAEAAYAPT/' +
  '9f8RABAACwAAAB8A/P8XAAsAAwANAAoACgAWAP////8LAPT/+v8FAPj/8v8IAPr/AAAKAPL//P8IAP7/AQAEAAcAAQALAAwA' +
  'CgAPABMADgAOAAkAEgANAAkADgAFAAUABgAFAAAABgAEAAUACwACAAMABwADAAgABQACAAMABQAFAAIAAgABAAEA+v/9//z/' +
  '+//8//n/+v/7//j//f/+//3/+v/9//z//P/7//j/+f/9//3/+v/9////AAD+//7/AQABAAIABAACAAEAAwACAAUAAgABAAEA' +
  'AQD//wQABAACAAMAAwAEAAMAAgADAAIABAAEAAIABAAEAAMAAwADAAQABAAAAAEAAQABAAEAAwABAAIAAgACAAQAAwAFAAQA' +
  'CAAIAAcABwAKAAcACQAHAAcABgAGAAgACQAIAAYACAAGAAYABQAHAAwAAwAEAP///f8DAAcA+v8EAAYACQANAA0ADwAQAA8A' +
  'EAAPAAAABADL/5kAXQFsAUn//v/K/1P/EAC1/27/vv9V/2X/bv+0//T/DwCB/+j/AgB8ADgApQApACUAeQB9ACIA+/+jAAcA' +
  '0//t/2P/+f8p/4MATAJZAGD+dwGiAPAAIwGa/8f+gv/N/rD9NACCAT4CMwGFAG3/yv+LAIEA6v9C/8//5f3e/cz+w//i/kr8' +
  'Pf3K/or/IgGB/5QAyQEDAK0AoAHu/87/rwBTAIwAmAFh/3wBtgDGACUBawGa/3oCPf/H/ysABAAnAHMA4P5PAJr/V//B/isA' +
  'T/2MAMr+df6OANb+L/4eAc/+U/9xAPn+WP9QAC3/QgD4ADkBwv/+AqgA+gEAA6sBbQODAhECAQSkAbQCnAFbAqgBPQDTAMX+' +
  '6P7s/138MP38+0z7Nvka+133PPcJ9pr2wvoy+pf7u/16AdcCNAXpBZ4IxwrPCcYIughEB5AGqgTgAlYCvgI4AYMBYwJwAhgD' +
  'egP5AasD1gInAZ0A/wC2/U78fvrq+Af3NvUq8nnwE/C/7fvugO4X+KMACP2l/mMHaA2zDRQPeAwiENMQwgeuAa0DRwDK+9r5' +
  'wPct+4n+2vtc/S4GtgjyCZgMMQ77EHAT3AsjCUsKogSJ/WX8vvnh9mH1AfHB8LLxfez/5uHngOYo5UnoX/eJBzb9qAGPEo0c' +
  '7hF+FTgT0Be1EPgBK/swAvX5MfBc9Sj3zPfP+IL6xP9eCoQHaAoXEYsUyhBoE1YPMA9VCisD4f8X//L5d/fj9pDylvK28Hnr' +
  '8ug+5hviIeEw4i7pJwZEBM/5nhJwILcUBxHUH4oWzBTBA/ABWQIt/bPrLvia+/nxuPEi/K/8Mf85AgsH4g7oDXENFhV1F5YO' +
  'OxIZEMQIeQNnAKj8j/va9VnxHvT973fpXuma5m7hk+BH3zTi3fJgCD397wS9G5wc8Q+QG94hgxQuD7sIUgcBAYf4PvEJ+8H1' +
  '9eyq82j7QPbY+VUDYQaFCmYNBxAXFjQW1hHnFS8VCglfB3EHR/8P+sr5gfUk8WLuCurM6PvkBeAB3+bg8t525hn5ZQbQALUI' +
  'vx/JGJoVkx2+I4YTSBH8DDUIVQBJ+GL1jvbU8TfsbfOD9NDyb/d1AEsDiwf/DGkQxBQSFtkWERf+FewOUAzvCOEC5/zE+bT1' +
  'YvHT7Zfpkeep5B7gMt+43xveqeNJ8isCVgD6A3YWRxkYGM0c0iB7GY0Y9w+PCUkHz//y9gz30PU27wHxZvCt8ML0r/gq+6IC' +
  'OQjOCpkQXxVwF9MYaxiRFJgSeQ4OCGwDMf4L+Hf03u9t6sTnj+Tm4Lffl9823ujfFuiv9AYCuAN3CNkT6hmqHVMgth7NGf0X' +
  'QRGmCU4EjvzM9jv1PPPw7yTwIO/+7xv1OvnD/PUB0AZqC8kRjhXIFjUYzxcNFlwTJQ4ACDcDt/09+P7zK+8z64PoG+V+4kLh' +
  'OeAf4MLhBeeK8ZL/BgV/CCkQFhbxGxYhYSAXGzgXFBG6C4cH+v8g+QP2VPMK8r7yZvG58CXzffb/+tsAkASjB+oLrw8CFGsX' +
  'EhfaFBkS2Q08CngGnwCg+jz1yvAa7knrH+ic5QrjfuEc4krjx+YY7nf57wK+B6gNtBGZFR8b/B1RHHMZYxNcDawJawQp/yr7' +
  'JvaC8/nzMvNw86n0FfVy9/H7EQAlBVUJjwvUDsoRDRMoFPYSZQ9BDDwIgwOp//j6RvbS8jvvmuxf6jvnDOXs4zfju+R36Dju' +
  'Z/gUAjQHLA3QEMwSXhekGRUY9hbHErANwQquBdoARf0t+O70DvQg8j/xNvF58LHxgPSm98D8pwKZBlAKJw58ELsSKxRtE9cR' +
  'Lw9pC4AITgU2Aef9OPqL9qH0hfKB8OLvMe9r79Hxx/TB+Bj+cwLEBdEJsQwHD/8QFREtEPkORQxJCecFjwHM/Wv6/fYu9B/x' +
  'LO5+67ro7uZ15q/mcejf6zXxb/loAOUEMwqbDXIQJhTsFQEWJBV3EjcQeg77CtsHOgSY/6z8Z/ot+ED3RPZ29Uj2fve2+aT8' +
  'rf7NAGID5wXCCHULFw0pDkkOTQ0qDCAKMwcgBJ8ARf11+qf31/Qh8mfvKe1N667preh46Pfo6+p97pLzPfocANYE0QmnDWAR' +
  'BxVeFpgWihXDEqwQig4yC4cIBQUZAXT+pPtZ+T34gfaR9eT1Ufa/96z5Avs4/XP/mgEzBGIGWAhiCq8LwQxbDaoMMQtQCbwG' +
  'LQRVAfz9v/rF90b1avPG8SXwoO4F7arrN+ty6yfs2+2o8AD1LvwoAnQHVQw+D9cSPBY0F2UXLxWoEf0OXwyVCRwHOwOu/+v8' +
  'bfrv+N73TPZJ9aT0JPWp9qv4Yvpm/GT+6ACIA/kFsAfRCI8JRQosC6YL9gqyCawHjAWZAyoBh/6g+3L4AfYz9AXzHvLg8J7v' +
  'mu7l7bvt+e297l/wZfOy+Ev/kARfCkAO4hFIFU8WoRY+Fa4RoQ7pCuQHLgUoAmj/8vy4+jf52ffE9pb1pfT+8+TzHvSx9JP1' +
  'APfu+JP7K//4AjYG2AksDKAOiRDwEDoR5A9hDT4L9AeXBRgDYgBh/g/8E/ql+Or2yfVo9Ejz3/LU8sjzifWj96f6hP3MAOID' +
  'OQYICLYIswhVCFIHswZIBgUGHgaUBfkECgSgAlUBx/9A/vH8n/ut+tH5Nfm/+N/3sfYH9QTzDPE97zXu/O0r72DymPcX/+8F' +
  'dQ1uE8IXrRsYHGAbjBjEErUNTQdRAoz+s/qe+B32pfQX9CjzlPNb86rzvPQL9vH4TfzN/4gDLgZ8CMAJAAqdCQsIKQZNBKUC' +
  'UQKJAs4DGgUXBsIGfQabBe8DXgGt/vf7yPlm+LP3kveJ9x73GvaZ9Gfy9++Y7ZHr1eqN6znutPP++7gGuBAOGr0gDCQ+Jcch' +
  '9Ru5E6kIhv/v9iXyMfB17z/xevJj9Gf2UveJ+bX5Hfsb/Wz/JwSsBzMLtQwOC24IEgPx/Sn57fXH9eL3Qf0UBG4LwBGpFI8U' +
  'wxDZChsEtv1o+bD2SvZ49/r4ovpS+pr45/XS8pnwi+6r7ePseezY7DztTvA89gEBRxHwHKApaCyHKf0i2BF2BTP2j+q26tnq' +
  'OvfR/7YFlwiuAUn9NPWq8aDzr/WQAPoGwQ8bE00OpAmL/VX2XPIv8KD2tPrpAc0HsQlaDP8JJQnMB/0GGwheB+8GFAO3/mz5' +
  '6/QA9E3zF/aM+Bj7hvx5+o73evE87Kfn1+Lw5e7oE/wFD60d/S1jJvkiEBPQ//z8HPFx96r81/9/CS0EqwM6/3v7wP9j/psD' +
  'PgBB/a75pfU9+4//zQnEDioOGAmf/D/03u3I78D3YwAVCqEMuw0uC/oJZwuBDDoNJAiJ/gbz8Ots7CP1AQInCsIJ1f5A7pPh' +
  'kduw3DDh9OYs7NkATxH/H/8t5h8yHsQJ8vim/I/y1/4vAakAJAZYAesFzwjFDA0PJgg+/g/vU+lG6t73PgmfE/oY7gxtAIz0' +
  'G/BD9nb8kQLxAKD7kfmY+7UKLxkmJPkgjAyi99zmZuU389cCNw7XDLH/IfL06ePqxvHG9Yzw1eIw1eLQqOU1EP0myUJJLHoU' +
  'UAKI6ND77gImCdkPlfpT+b/4JAG6F5Ab1RfNBBzsMuAl5efycgrEFogUEA6q/pv4uvsm/R4CRPsi8Sjud+/DAskSESG0Ij8U' +
  'Owgn97P0NvkK+6cBrf39+5r9sPvp/iv7bPI56jjfUNik1sjWqOsjEQsgKjjTI1YTRAnm9xMEPARf//3/avLy+RcHnRRdIMoZ' +
  'NgZA9bXm1ebg9AT9KQu8CpgKRwycCP8HmwJt+JrwC+kh6pb0tgK3EiUcLB42GqMRCgY9//v2BfS89AP3//zEAtsDaQDO94vu' +
  'aeik43jgB9iH1OLVQvsmIiQ1nT3oFTwGivhI+xQMiwVd+Xzt3expBPMgECkMIBwDSeyT6JzwVvyxAaH9T//wBQoRGBqkD2P/' +
  'VOqr5H3rvfbrAbYEJQnDEUYc3iCzGbMEovWn7pf09P4uAij91va19dn5iPxJ9EXo9do4027VF9rY9sIgZyiIOCYUqAeK/2wC' +
  'LQgoAzPs+uqo7wUOxCioKEcTqvrQ7Ar5nwJVATj4pu7J+cUQIx1hG8AD5e8s63rv//ha+QH2bvklBmEaoyUSH88NbQBP+mL+' +
  'e/wh9arws/IA+zkBW/258uTnet+H3cPf1NtQ4NEKBhtPMyIldA2ABtQH6ggVCgH1G+cs75wAohn8Hr4RkgMc/gECEQUJ/Fjv' +
  '/u5P+uYLBhZaD7QGaf+c/HD+jvej77juJ/XmBw4Y/xmgFi0QlA05DHUFM/ij75fs/vDk9kf0iu6/6j/q9eqy56TfMdug4f0Q' +
  'pB86KrQZhgUHDbkYChaQCs/uGOSY9ZwK5xNcEkz+YP+iCJ0NhghG+L3pYPIrAp4LLg1yAUr/DQK6BsABHPkt7+rznQRyDiQT' +
  'rQz/CccPExf/EeoDh/P+61TxrPMv79HnQeNs5i3rCeuv4zbeht/kA/If/B0MHY8CNQ9/HAEiGQ7P+YXquvbuClkKWwTL9236' +
  'Jwl1EwcJuvpZ8Sn1ygb8CXsD9Pm7+eUB5wsECP38TvXu+dYHlxAeDEwFMAXiC1ETwRAgA9f4R/T/9U72RO32453gQuKu5NPj' +
  'Ut8/33TxrRDLEcIV4AthDoEeNCW0G9ANhf8V/6wHswc6/XT17vAn+j8FBQPV+4D45PnFBVINdAd1ATD+xgF6CAAIXABJ/K77' +
  '5f5JBNUBovxf/H0A3AWhCpwI2gSRBMYElAWVA73+4Plk9kHyiu7m6n3nvOXL56Tr7Oux6zTuvPKy+44DAwjTC8UPMhUoG2ce' +
  'hh3XGhcXBhRGEQIN/wa7AAD8X/kI+H33QfbH9Vj2b/fr+RD8Jv12/msAbALvBAMG4wUkBv4FAAbPBZIEMAKG/+D8Gvso+S72' +
  'y/J87wLtuOsb6/vqveu+7prxS/RT+Bv9CQO5CXoO5xGbFEsWrxcOGOYVbRJiDr4KWQgxBicDFgBZ/bv7m/tO+4n6evlb+N33' +
  'ffhN+VP6Vvum/Kf+GwFdAzUFvgbvB90IOQmkCCoH9gRUApH/h/wv+Z31KvJX70vt/etJ65XrjO1L8BTzP/bJ+Sz+gANvCFkM' +
  'Vw8oEWISSRMxEzkSihAuDuELmAkAB6UEZQJSAML+c/0m/AT7Bvpn+XP5rfkC+rP6l/vI/Er+k/+6AOMB9ALAA0cEXQQKBGQD' +
  'WgJDAUYAKf/J/Tj8UfrO+Oj3GPdp9rr1avXx9QX37PfM+Af6q/vw/XgA1AK7BA4G+QbYB7wIjgkRCvgJMgkKCOAGBAZfBZsE' +
  'gAMeAtgA8v9j//3+pP5U/hL+8P34/Tn+qv4m/4//zv/g/+//JQCCAOUAAwG6AC8Aqv9n/0//A/9f/pL9wvwQ/I37Q/s2+1H7' +
  'avt1+5n7+/uO/ET9HP4T/wwA0wBIAXUBkAHtAZUCIANGAwEDngJuAnYClwKwApwCWAIEAr0BpgG1Ac0BxQGYAVkBJgEGAf0A' +
  '9QDRAIUAIADG/4b/WP8y/wL/wv6C/lL+Nv4w/jj+Rf5T/lr+X/5v/pL+vf7k/gX/Kf9W/43/x//1/xsAQwBsAI0ApgCzALYA' +
  'qgCdAJQAiABvAFQAMwAXAAkAAAD//wEABwANABsAMABMAGQAfACQAJ0AnwCYAJAAiAB+AGwAUAAyABQA+f/j/8//uf+o/5v/' +
  'kf+P/5L/nP+l/63/t//G/9n/7v8CABUAIwAwAD8ATgBWAF4AYwBiAFsAUQBDADQAJAARAP7/6//Z/8r/v/+4/7P/rv+t/7D/' +
  'tf+9/8b/zv/Z/+T/7v/2//z/AgAHAAkACgAKAAcAAgD7//T/7v/o/+T/3//c/97/4P/l/+z/8//7/wMADAAWAB4AJQAqAC8A' +
  'NAA0ADQAMAAvACoAJgAhABwAGAAWABAADQAMAAgABQACAAEAAgABAP///v/7//r/+f/5//b/9P/y//H/7v/o/+f/5f/j/+T/' +
  '4f/h/+P/4//j/+T/5f/o/+r/7f/w//H/8//2//n//P/8//7/DwAwAH4AbQE+AMcAlP9oANf/dAHuADz/8/8u/6X/KwDL/88A' +
  'gAKyAOIAtACNADEAiP8M/vX+uv5R/mP+Nf4F/9v9RP6//p795P8N/vUB1QEQAn0CzQDB/5IAYAAPAE7+wf+D/T3+3P0b/1H9' +
  'w/8k/Vb/7/6s/yb/w//c/5EAOAD3AH8BIwQwA74BDQIvAskCLAPNAXoEUAGyAOP+7v2p/y7/NwBj/7UAAP8KAmT/SwHAAIIA' +
  'eAC/AQgBRgEXAdcBPwKu/0cAG/9N//X+gf61/R7+xv7u/B7/L/5JAMb+mQAD/+oAGgBVAHgAjv9bABj/bwGh/h0BwP79/7T+' +
  '2P/l/kMAUQBDACUBCv/HAIMAbQDs/5wAgv92AM//Kf/FAan+hAG1/mQAnf/m/xX/0f50AKv/1//k/0//Yf9/AY/+8gDs/ygB' +
  'Yv8iAHn/5wDl/tMBSP0RAhP+4gDN/+H/yf93ADf/z/8UAMn/mP+rAN4AZv+AANj/eQBVAQX/1QAxAK3/WgD7/x0AyACp/2YB' +
  'Fv+iAdn+zQEy/psAvQD0/xgA4v/2/zAAaf8VAHD/gwC9AD/+dQHP/oABmv4DAj79OwEQALf/iAAQAKv/+QBP/5AAHP9UASgA' +
  'Kv/wANv9vAJi/f0ANf6MAp/+wABT/6wAbgC5/08Ab/9lARgAeQAAAPX+swD//nMBLv/x/1wANgBCAO/+EgHy/z8ALf8B/5sA' +
  't//G/2v/Wv/5Adb/5P5NAMb/VwEL/zkAZf+VAav/Rf8GAFQAiv+QACb+m/87ARP/NAB7/mIBGP9RAHsAAf9sAl3/AwG//2UB' +
  'kwBYAYQBNgBKAoIBAwKDAZcBcAJPAUICFAC2AWsAkgBc/zD/uP8q/rj9Nfy+/S/9S/y5+kL7SPzL+wD6yftt+nb8Z/oA+g77' +
  'Uvth/Pr7gv47/4sBLwMkBA4IsQlYC68Kmgx9DEIMwAkDCPgGiwTuAvv/7/8t/qr+kv3v/WD/VAFtAh8DoARQBVcGxQVNBH0D' +
  '9gGk/+f8Yfrs9/P1C/SL8VfwuPDQ78Lu/e4t75rv9PAo8zX2CvzbA/AC4AQaCvMOlxEoEhASRBIUFJYQVQs9CQQIuwQZAGn8' +
  '4fn3+VD5gPe+96L7Zf4qAIkCTQWBCaQMkA0JDXoOIw/1DGMJ8QYuBaYC+f6v+uz3zvaq9L3wce7q7R/tHet16STofecy6Bbq' +
  'oO1c8nX7Ev1CAFoIDxD3FDwW/RoHGlsdbRsTFgEQkQ/lC6IDLv0s+sn2uvTf8uzvF/Cs8yr2XfW2+IL9yAGjBNAHpQmpDfER' +
  'ZhKnDzoQJhGpDgULrQfQBM0Bsf6f+b31i/PX8fbuLey46hrqlOgk51/mKedA6izvXfXm99v6iQKQCRkPvRFpFw8Z4RsFHYwZ' +
  'hRXCE+4RSApnBJQA2fxF+E72ufFW8ETxi/K68Nzyrvae+en7Pf/wAX4Fdgq9DHoNHxDfEoARARD1DgUNAQo5B58CS/7q+834' +
  '8fN08J3vye3766DqvOma6Ljosug/6RbvyfZB9r/4NQBcCNcMSxAZFaUW3BszHEAZ6xTAFMURFwuyBfoBQP3o+Q32kfJI8OXx' +
  'APKc8CHybvXs9yr6Sf2Q/1gD+wfkClwLtA7BEYIRChCXDzwOKgwUCq0FtQC2/rD82ffL8/nxQvCR7kztn+u76pvqvul16Grp' +
  '9+7R9q720feN/7sHwwzzDgEVbBbIG5QcwxkyFaoUGBP7CyIGFwLs/Sj68/Ye82vwTvE78uPvSvEc9MT2LPh3+7P9CAE5BckH' +
  'vgh8DMIPwQ+BD7gPog5lDYQLawdeBKoCPf9n+vH32PWA8xTxqO9l7iPupu187NTr2+vb7IjuEPTX+en54/3JA0kKZA3vECwU' +
  'dRWCGOIWOxSpEJoPEQw6B9cCCf8p+8j4kvUt817xgvH98Ijw3/Bp8U/yPPOj9Jv1bvkN/xUAqQEkBoMLYA7TEDgTIRPcFbMV' +
  'gRIcDroNYgtbBuYBN/45+qX49fXA8v3w4fLG8hryIPP/9Iz3l/pq/WH+pwHEBeMHsAhGCw0NYg4qD4YOlAzoC7AKkQeFBDwC' +
  'f//C/OX5APcX9SX0i/K58GLwVfDc743vi+/87hTvOfDD8kD4Zftt+9n/SAWCCgQNbhEHE64V5RcbFkcTJhGFEAEM+QdNAyD/' +
  'zvvW+UD25PPj8030lPNN9HX1ePco+un8nf5LAXkEhwZwCJ0KyQujDE0OGA55DEoLAApcB9kEJwLo/jX8Tvqn9071OvSk86Hy' +
  '8fFd8t3ylvMt9LL0V/QL9HT0+PQV9yv7APy0/IP/NQNQBUIINgu/DLkOTRC1D/wNdw0oDNYJggfTBPIBGgCL/sH8vPu5+6/7' +
  'ovsL/M/8nP3V/u3/5ADYAdYCiwMdBIQEowS0BJMEVwTFA0ADRwJHAV8Anf93/qT97Pxv/Oj7d/uG+6P7u/sc/Gz82vxr/dX9' +
  'SP7J/hv/d/+v/+n/5v/2/9j/yv/F/37/b/9J/yD/MP8F//n+xP7c/tb+2/7i/hL/Fv9L/2r/pf/0/0YAfQC0AAsBOAGKAZUB' +
  'tgHYAeYB3gHbAbEBjAFcATkBEQHjALQAbgBQAEMAJwAeACEAFAANABQAKgAbAC4APgBJAGUAfAB3AKEArQCsAK8ArQDFAKcA' +
  'oQB8AF8ARQAeAAUA0/+r/37/Zv9H/z//F/8d/wj/Iv8D/xH/Mf9C/3X/g/+X/8b/zf/z//D/MwAaABsAGQAXAAYACQDd/+7/' +
  '0v/Z/8j/1P/K/83/1f/Q/+T/AAD7/xMAGAA+ADwAUwBUAFkAdwBzAIIAhAByAI8AcwB9AFUAXgBTAEYAHgARAAQA6f8NAAIA' +
  '9P/i////8/8DAAgACgAUABkACgAfACoANQAwACYAJgAYAC4AAwAeAPn/HgD6/+H/z/+//9//4//K/8//5f/h/+f/3f/5/wIA' +
  '+v/8/xoA8f8SABsAJgAmAC0AJQA4ADEAIQDw//7/IQASABEA6P/N/9j/8//m/woAHgD8//H/BAD5/xMA9/8fACIALwAzACQA' +
  'FQAKACEAIwAKAPv/MwAKAOz/EAAQAAIACwD4/wAA6////9z/0f/j/8z/HgADAPj/FAAHAAYAFwAIACYAGQA6ABEAEQAHAAcA' +
  'FwADAAYACgDw/wgAFwD3//H/2v/g//f/2v8EAO//9P/8//j/9v8WAAwAFgALAP//DAACAPT/+f8RAPv/FgD6/xIA7f/9////' +
  'DAD3/wUA9v8BAPz/FgD6/w8A8/8FAPn/+f8BAAYABgAqAA0AEwD//yMAHAD9/wEABQAGAAgA/P/8/wcA8f/1/+v/EQD3/w0A' +
  'CQAEAO3/+f8SAPb/CgD9//v/EgD5//n/9f8ZAAMAEwD9//b//f/r/wIA/P/c/xcABAAMAAQA4v/7/wMAIgAMAP7/AQDq//z/' +
  '+/8AAPv/+P/n/+//IAD9/+X/JAD+/93/0//j/wIADgACAP//BwAfAPz/EADs/wMAAgADAAYA+//s/wsAKwAOABsA5P8cAPr/' +
  'BQAFAPX/BgD0/9D/4v8CABoA6/8NACQAFQArAOv//P/5/woAFQAyAA8ABADt/9X/DQDV//X/9v/3/+P/AgDt/8f/BwBFABoA' +
  '7//H//j/4//z/9//wP/m/xkA/P8WAP3/7P8CAPr/EQAfABAAFQAeAA8A8//r/woA/P/u/+3/+f/w/yEA///p/wkABADm/+b/' +
  'zv8LADMA/P8aAAQABgAFAAoACgAJACIA6P/n//T/7f8mANr/CQAoAPX//P/R/xUA///5/+P/1P/L/wAACQDo//v/6f8HAA0A' +
  '5P/E/xIAJAANAAwALgD3/8v/xf/Y/x8A5v/5//b/t//X/xwAAgCo/yIA0P/H/7X/3//r/18A7f9BADoAdAAmAMn/k/+k/wIA' +
  'cQAWAJL/HgBKAO7///8kAIEAqgA+AYEAvP+p/83/CQDz/w4Auv84/+H/IQBB/73/EP/Z/5wAxv/V/24BkQDNAK///P9I/y8A' +
  'PwB7/5//c//m/7YA5v/EAMMAaAF6APj/9v8N/7//mv5G/wIBxP/r/+L+8v+O/+n/YAB1AIoA8f+JAMf/qQANABv/tf+e/zn/' +
  '4/+W/zn/NwBbALn/EQC0/7IAfQDvANwA3gAwAXkBmAGfASkBgQEwAQIBSAHEALUAsQBEAOD/0v+j/y//FP/T/oz+gv4g/u79' +
  'gP17/Rj9SvwJ/E37JfsF+7T6xvmB+fj4lfgH+EH32fjk+gUB/AfwCCYLcQo1DGgPixEUD7QJogU9Ap8Asv/N++f3kfZY+Mn7' +
  'DwD1AWgB5QK6BOgHCgrYCFgFLwLbAIkAUP9p/IP4pvb090H7ff4UAAgASAG4BFQIiArACVUGbQNAAtYBxQDy/XX6cPjB+Ib6' +
  'rftZ+336k/pd/Cr+UP7H/B76Qvgs9/D1XvTd8dXuJO2m7WPxT/fVAO8NOBH0EdoTfBN+GO4asRW7DTYDJf2E+974TPdH8pHu' +
  'L/FR9wz/4wRJBUQFPga0CeINVg5zCpgEPv8s/hT+3fzQ+eD1CfT09fP5Lv7T/+H/kQDiAt0GtAn/CF8G4wMuA/EDxwO8AYP+' +
  'afwN/UX/9wCyAJL+5PzC/LL9Vv4Q/Uf6xve19jv3d/d79vv0v/Oe8wf0q/Na9Nj2qADHCwMRqBBLDYkNeROsF7QXbRBYBR3+' +
  '6/qy++37XveW8YTuK/Ft+XgAIwSYAwoCvgOSCFQNVw+eC24FbACh/sr/SACp/Sr57PRG9G/3rvu+/hX/G/6a/k8BhAVuCFkI' +
  '1QU6AxcD/gR1BroFzAL2//7+wf/wAOcAV/9S/ev75/uM/Lj81vta+nD5fvkY+of6PPqx+Q/5cPj994n3D/du9vX1IPf5+ooC' +
  'AAtPDk8NswqwC/kQBRWKE3EMZQM1/mP8ZfyO+2r41vSp8qrzXfjs/c8BgQIrAWoBVwTwCM0LqwpnBkcCQwDBAGwBjACp/TT6' +
  'EPii+An7kv15/tv9fv2T/hUBuAMLBeQE5QPmAu4CrAOxBAIFwAOeARQABgAHATkBHQBx/mj9hf3p/c/9VP3+/Ef9sP3P/bn9' +
  'bv3d/Br86fqa+WH4LvdC9kv1QPRK9Er2KvxlBJ8JQgp0BxIHZwu7EOoR+QxZBUQBqgBrAan/NvuT9432Dfhu+sb73vzH/Zn+' +
  'rf/ZALUCdwTFBLADTQIcAj0DtQPVAhIBIADIALABrgHOAAUASgCjAHgA0/+Q//r/RwC8/67+Fv6K/hv/0f6j/Vz8r/t/+yv7' +
  'afop+cb3v/YQ9qn1MvVD9ef2yvuuA3MJqAoqCHYH7AsoEvcTig4/Bc3/hv/YAPX+Z/nW9FX0VPcA+1b9W/+WAXIDpgRJBXUH' +
  'AwpICugGhwGs/qT/CwGq/7X6J/ca+FP8EwBhACD/QP9VAYUE8gWGBbMDTAHP/zn/c/8u/yz97vpo+uX8fgARAmEBYACGAWcE' +
  'EQYfBVMC9v9Z/3n/Mf+g/WL7M/oK+4z9NgBbAV0BqQGfAzAGJAeeBSwDFgK2AtECMQF//hb9yv0Y/3L/rv4n/sn+6v+jAFAA' +
  'dP+m/hb+wf1X/cX86/sh+xf70vuc/IX8kvvM+ur6avsM+3L53fg6+xgDHglLCbAEbwJ4B0QOTQ5yBwD/bf7lAeYC/f3C90j3' +
  'NvxHANEAcf4R/5cCQQYAB5QELgJoAXMBXQFL/8n8K/tq+yb9Sv5Z/kf+af/lAcMDrANkAogB8wFdApcBwf8d/r79T/7W/tH+' +
  'nf7o/gsAYwEWAt4BggF/AcsB0QEZAc3/w/6U/vL+4P4S/if9K/0e/sL+FP68/Dr8Hf2v/Xb8Qfou+bn5KfrL+X37rwMsCqII' +
  'tQPKA44LTQ84CbwA2f3qAdICs/xK9xr4nf5wAuX/0f1GAHYGmwlpBoQCMgIWBOIDwv6R+l36ufzS/VX8ofts/vEBYgTJA/QC' +
  'IgRYBZwEcQGS/oX+bv4H/cb6e/rr/Mf+H/9C/8EAfwNpBMYDkAI4AkwCLAEe/0f9xPxq/VH95PzC/B7+XwAhAdYAEwHAAiAE' +
  'LAMxAY0AMwEPAQT/uP3r/pgA8v/+/vf/XwIuA/gBPQELAqsCoAG7/zX/gv8a/zD+Mf2R/Wv+e/4G/nH9uv09/mf+zv0J/RX9' +
  'AP0F/MP6FPoN+nT6j/76BC4C9wDZAy4K+AtyBd0CuQYMBigCjPqD+4L+4/19+x76Rv1LAm8CigIWAmQFEwhVBe4BiwDoAYkB' +
  'm/xw+s/7dP3x/Fj7pv3pAHECxgLFAkYESQVbBNEC0QBpAK3/wf3V+1b7KPzB/Kb8dP3l/pMAggH7AXYC1wLKAgUCzwAuAHj/' +
  'kP7F/Xf95v12/v3+Mf9JAKcB5QEiAiYDXwTOA/4BBQKOAisBdP+0/i//MP8u/gP+kf5D/3f/bv/Z/9T/Hv9Y/h3+5/19/MH7' +
  'bftG+lz5bvh1+En4c/5JBGf/CgBGBmULqAjeAgAHfQmOBPD+fv3f/wT/P/qn+mj8oAAUAHf/xQGoBS4HJQUIA20FbwVzAp7+' +
  'vP2i/r/8X/qF+sv87v1//Wj+VgG5AvQC3wK6A6sDlwJKAVYA8f7x/Tz9rPwq/En8Lf39/ZX+hv+7ALABKwI6AmMCWwLrATIB' +
  'WQCm//P+Yf7+/b798f1R/sD+Rv8MAO4AbQGHARICmQKRAh4CsQF8ARYBlQD3/4H/qP+y/z7/Of/l/10AcwB0AOgAXQH1AGQA' +
  'PAAcAC3/EP64/Rn9Z/w3/Cr8sPt7+1r81fxh/Gj8Kv2X/TP9yP3R/pEDpQOO/7cDBwg1Bh8DkwN7B+cDRQByAGAA3/9N/Un8' +
  '3v4+/8f/nv7xAEUERQMBAlMDsgRgAzgASABvANr+3/wq/Cv9fP2v/AH9x/5BAH4AcADYAf4CawJeAWUBcgFNALr+LP4d/rL9' +
  '6Pzl/Lv9j/7A/i3/WwBxAYsBoAEbAi4CngH5AKkAQgCJ/+b+vP7S/q3+kv7v/mL/xP80ALQANgG6AewBpwHQAQoC0wEoAdoA' +
  'MwHGAAAACwASANb/rf+0/93/n/9O/z7/HP8s/7D+Ef6u/Qf+vv1l/HX8nfwi+4D6JvvJ+WL+9P+t++r+VAQPBC0BXAPgBwAF' +
  'qAKTA9sDpgJ7/xv//gCf/wP+3v3UALoAU//8AA4DbQJrAegB2gJ1Adj/xP/z/7z+d/2y/U7+Cf6r/aP+8v/z/+X/6wDCAX8B' +
  'AAFyAWABsgDh/5//f/8A/2X+Sv51/qP+yf4U/87/XQCQAP4AcAGGAXkBYgFdATYBFQGAADMAfABJAMX/3v8pADgAw//x/5wA' +
  'gQDl//r/DABg/7j+1P5J/sD9N/1C/Vj90vyM/Pj8L/3A/Ij8xfz3/N38zv44AUX/XgCKA6MD0gLWA1UFvwRDA/QCyAImAjwA' +
  'gP9LACT/Mf7e/s3/b/+c/+IAiwGRAcEBGwInAlAB5gC4ADcAQ//c/rT+sv6U/sH+Rv/o/yYAcQAiAVUBXQHeAWwBAwHDAFsA' +
  '3P9g/zb/EP8D/xr/Xv+0/+H/EADeAAsB9ABBAToBwQBhABEAc//L/ob+6/2Q/TP99Pz//C79eP2I/YX9sf14/jj+Qv7k/ob+' +
  'nf0A/ev8Cfxb/ekBef6E//8D2AOHAg8FAAe3BUQFoQXWBAQExgHfAeEBqP9i/lP/P//7/fv+ngBpAEoAAwGzASQBhgD6AMMA' +
  'sP/8/lf/S/9z/pf+Xv9d/+j+gv+CAF4AOgDhAPYAbwAtADcAvP9N/wL/qv72/oL+J/4V/7f/kP8vAEYBKAFfAc0BcwG/AZ8B' +
  'CQGcAJMA7/8v/1v/K/9b/mL+bf4j/u39Lf54/lz+Of5P/tf+VP4z/ob+Of4Z/l3+Zv4s/t/+KP/u/iD/t/6m/kz+Q//7AJAA' +
  'gQEiAwsDxwIABGMEygMdBD8EVQPiAr8CHAKzAUAB6wCaAFEAGwBaAEsANACEAK8AaQBcAIAATgAFAA4A7f+5/6v/ff8//y7/' +
  'Cv/J/s/+9P7H/pL+mv5W/ib+CP7V/bH9ev1u/dL9mv27/ez9+f1A/cf9nv4b/pX+cP8a/w//If/9/jH/X/+l/wkANf+m/7P/' +
  '6v+eAOYBsAF5AqcC+gGMAjEDCQNeA7sDNQPBApMCbgInAvQB1wG/AW0BIAFGARwB5AAAAQIBkACYAKYAaQA3AEgALADH/7n/' +
  'vv9w/2L/Yf8F//r++/6f/sb+tv5C/lT+b/4B/hb+Wv76/df93/24/bz9+P0P/iL+Hf4o/lP+oP5z/q/+Nv/N/hT/4/+6/27/' +
  '5//W/67/8/+bALQAzQABATIBDQFGAf8BDgJQAnoCTAIYAkACPQJJAnECcQIOAtcBlgFwAUoBNAEgAfMAtgDQAI8AMAB0AD8A' +
  '9P8aAAYAxv+u/5X/l/9x/0n/P//8/rj+t/6V/nj+l/5n/i/+PP4+/jn+gf6P/pX+sP6P/uX+3f7b/gb/MP/7/j3/Zf9q/5D/' +
  'pf/B/9b///8NAE4AbgCpAOIA6wDsADgBJwEkAXABLQEPAUwB7QDMAC0B4gCeAOIA1QCEALYA4ACuAIkAxQChAG4AbABlABEA' +
  'EwATAOr/9f/2/+z/qv+w/6n/ov+Y/7z/uv+N/5v/l/+W/5b/p/+j/7H/qP/B/8j/vP/K/73/zf/b/93//P/7/+T/5f/v/+7/' +
  'AwDs//P/3v/B/9n/zP/F/8r/yf/R/+v/7v8JAAwA5v8XAD8AMQBPAGIASwAlAEYAVQAzAD0ARAAOAPj/EgALAPj/6P8CAPP/' +
  '3P8dAC0A9/8fADgA/f8FAC0AGQAGABgAKAAPAAIAHQAVAOr/9v/5/9X/2f/x/+X/1f/c/9b/w/+p/8b/0f/P/+T/+//8/9z/' +
  'AgD6//r/DgAVABcAFQASAAMAAQDs/+n/6//u/wEAAADa/9b/6P/V/9n/6v/+/+n/7f8EAAEAFAAeACAAFgAfABYAGgAMABYA' +
  'CQDl/9n/2v/T/9T/2P/p/+f/4v/s//f/9v/4/y8ALQAkAD8AQQAqACEAJgAXAAIA/v8GAOb/3//U/7v/uP+2/8D/3//e/9D/' +
  '7f/k/+P/DwAcAAEAFwAbAPz/BQAJAAUABQD+/wIA+v/n/+//7f/O/+n/4f/N/97/8P/u//H/CAARAAoAFAAkACAAEAAuADMA' +
  'EQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==';

function fixtureAudio(): Uint8Array {
  return Uint8Array.from(Buffer.from(SPEECH_WAV_BASE64, 'base64'));
}

describe.skipIf(!deepgramConfigured())('Deepgram, live', () => {
  it('transcribes real recorded speech and returns word timings in milliseconds', async () => {
    const result = await transcribe(fixtureAudio(), 'audio/wav');

    expect(result.transcript.toLowerCase()).toContain('testing');
    expect(result.transcript.toLowerCase()).toContain('one');
    expect(result.transcript.toLowerCase()).toContain('two');
    expect(result.transcript.toLowerCase()).toContain('three');

    expect(result.words.length).toBeGreaterThanOrEqual(4);
    const first = result.words[0]!;
    expect(first.word.toLowerCase()).toBe('testing');
    // Milliseconds, not the seconds Deepgram sends: a fixture just over a second long would
    // pass a seconds-based assertion by accident, so this asserts the scale explicitly.
    expect(first.endMs).toBeGreaterThan(100);
    expect(first.endMs).toBeLessThan(2_000);
    expect(first.endMs).toBeGreaterThan(first.startMs);

    // Same units the worker's schemas.py WordTiming contract expects.
    for (const w of result.words) {
      expect(Number.isInteger(w.startMs)).toBe(true);
      expect(Number.isInteger(w.endMs)).toBe(true);
    }

    expect(result.durationSeconds).toBeGreaterThan(0);
  }, 30_000);
});

if (!deepgramConfigured()) {
  console.log('[deepgram-client.live.test.ts] SKIPPED: DEEPGRAM_API_KEY not set. Not verified against the real API.');
}
